sonar.projectKey=ressources-relationnelles-CDA-2026_Ressources-Relationnelles-Back
sonar.organization=ressources-relationnelles-cda-2026
sonar.projectName=Ressources-Relationnelles-Back

sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/vendor/**,**/var/**,**/tests/**

sonar.php.coverage.reportPaths=coverage.xml

sonar.tests=tests
sonar.test.inclusions=tests/**/*.php
sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=reports/phpunit.xml