# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\State\UserPasswordProcessor:
        arguments:
            $persistProcessor: "@api_platform.doctrine.orm.state.persist_processor"
            $passwordHasher: "@security.user_password_hasher"
            $rolesRepo: '@App\Repository\RolesUtilisateursRepository'

    App\State\RessourcesCollectionProvider:
        arguments:
            $ressourcesRepository: '@App\Repository\RessourcesRepository'
            $security: "@security.helper"

    App\State\RessourceWriteProcessor:
        arguments:
            $persistProcessor: "@api_platform.doctrine.orm.state.persist_processor"
            $security: "@security.helper"

    App\State\PartageCreateProcessor:
        arguments:
            $persistProcessor: "@api_platform.doctrine.orm.state.persist_processor"

    App\State\CommentaireCreateProcessor:
        arguments:
            $persistProcessor: "@api_platform.doctrine.orm.state.persist_processor"
            $security: "@security.helper"
            $commentairesRepository: '@App\Repository\CommentairesRepository'
            $utilisateursRepository: '@App\Repository\UtilisateursRepository'
            $ressourcesRepository: '@App\Repository\RessourcesRepository'

    App\Serializer\PlainIdToIriDenormalizer:
        tags:
            - { name: "serializer.normalizer", priority: 100 }

    # Singleton pour la gestion de la session utilisateur
    App\Service\UserSessionManager:
        shared: true # Force le singleton (une seule instance par conteneur)
        factory: ['App\Service\UserSessionManager', "getInstance"]
        arguments:
            - "@security.helper"
