name: Back - Quality

on:
  push:
    branches:
      - main
      - dev
      

  pull_request:
    branches:
      - main
      - dev

jobs:
  quality:
    name: Qualité PHP & Symfony
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: intl, pdo_mysql, zip
          coverage: none

      - name: Création du dossier de rapports
        run: mkdir -p reports

      - name: Validation de composer.json
        run: |
          set -o pipefail
          composer validate 2>&1 | tee reports/composer-validate.txt

      - name: Installation des dépendances
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Vérification syntaxe PHP
        run: |
          set -o pipefail
          find src -name "*.php" -print0 \
            | xargs -0 -n1 php -l \
            2>&1 | tee reports/lint-php.txt

      - name: Vérification configuration Symfony
        run: |
          set -o pipefail
          php bin/console lint:container \
            2>&1 | tee reports/lint-container.txt

      - name: Vérification YAML
        run: |
          set -o pipefail
          php bin/console lint:yaml config \
            2>&1 | tee reports/lint-yaml.txt

      - name: Sauvegarde des rapports de qualité
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: back-quality-reports
          path: reports/
          if-no-files-found: ignore