name: Back - Tests

on:
  push:
    branches:
      - main
      - dev
      

  pull_request:
    branches:
      - main
      - dev

jobs:
  tests:
    name: Tests PHPUnit
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4

        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: projetcollab_test
          MYSQL_USER: ressources
          MYSQL_PASSWORD: ressources

        ports:
          - 3306:3306

        options: >-
          --health-cmd="mysqladmin ping -h localhost -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    env:
      APP_ENV: test

      DATABASE_URL: >-
        mysql://ressources:ressources@127.0.0.1:3306/projetcollab?serverVersion=8.4&charset=utf8mb4

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: intl, pdo_mysql, zip
          coverage: none

      - name: Installation des dépendances
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Création du dossier de rapports
        run: mkdir -p reports

      - name: Création du schéma de test
        run: php bin/console doctrine:schema:create --env=test

      - name: Chargement des fixtures
        run: php bin/console doctrine:fixtures:load --env=test --no-interaction

      - name: Tests PHPUnit
        run: php bin/phpunit --log-junit reports/phpunit.xml

      - name: Sauvegarde du rapport PHPUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-report
          path: reports/
          if-no-files-found: ignore